spring.application.name=course-service
project.name=projectE
server.port=8082
catalog.service.url=http://localhost:8081
# application.properties
logging.level.root=INFO
logging.level.com.course=DEBUG
# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
# Kafka Topics
kafka.topic.course-published=course-published-topic